language: generic

dist: xenial
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-8
    packages:
      - clang-8
      - llvm-8
      - llvm-8-dev
      - lld-8
      - cmake
      - wget
      - tar

install:
  - export LINKLE_VERSION=v0.2.7
  - wget https://github.com/MegatonHammer/linkle/releases/download/$LINKLE_VERSION/linkle-$LINKLE_VERSION-x86_64-unknown-linux-musl.tar.gz
  - tar -xvf linkle-$LINKLE_VERSION-x86_64-unknown-linux-musl.tar.gz

script:
  - make LINKLE=./linkle

after_success:
  - mv rtld-aarch64.nso rtld-aarch64-$TRAVIS_TAG.nso
  - mv rtld-aarch64-6xx.nso rtld-aarch64-6xx-$TRAVIS_TAG.nso
  - mv rtld-armv7.nso rtld-armv7-$TRAVIS_TAG.nso
  - mv rtld-armv7-6xx.nso rtld-armv7-6xx-$TRAVIS_TAG.nso

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "rtld-aarch64-$TRAVIS_TAG.nso"
      - "rtld-aarch64-6xx-$TRAVIS_TAG.nso"
      - "rtld-armv7-$TRAVIS_TAG.nso"
      - "rtld-armv7-6xx-$TRAVIS_TAG.nso"
    skip-cleanup: true
    tag_name: $TRAVIS_TAG
    on:
      tags: true
condition: $TRAVIS_OS_NAME = linux
